/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.resume.user.panel;

import com.company.resume.user.config.Config;

/**
 *
 * @author x
 */
public class ProfileDescriptionPanel extends javax.swing.JPanel
{

    /**
     * Creates new form ProfileDescription
     */
    public ProfileDescriptionPanel()
    {
        initComponents();
    }
    
    public void fillComponents ()
    {
        fillUserComponents();
    }
    
    private void fillUserComponents ()
    {
        txtpProfileDescription.setText(Config.loggedInUser.getProfileDescription());
    }
    
    public void saveUserInformation ()
    {
        Config.loggedInUser.setProfileDescription(txtpProfileDescription.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spnlProfileDescription = new javax.swing.JScrollPane();
        txtpProfileDescription = new javax.swing.JTextPane();

        spnlProfileDescription.setViewportView(txtpProfileDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(spnlProfileDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(spnlProfileDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spnlProfileDescription;
    private javax.swing.JTextPane txtpProfileDescription;
    // End of variables declaration//GEN-END:variables
}
